<?php
return [
    [
        "text"=>"CHARACTERS",
        "url"=>"#",
        "active"=>FALSE
    ],
    [
        "text"=>"COMICS",
        "url"=>"#",
        "active"=>TRUE
    ],
    [
        "text"=>"MOVIES",
        "url"=>"#",
        "active"=>FALSE
    ],
    [
        "text"=>"TV",
        "url"=>"#",
        "active"=>FALSE
    ],
    [
        "text"=>"GAMES",
        "url"=>"#",
        "active"=>FALSE
    ],
    [
        "text"=>"COLLECTIBLES",
        "url"=>"#",
        "active"=>FALSE
    ],
    [
        "text"=>"VIDEOS",
        "url"=>"#",
        "active"=>FALSE
    ],
    [
        "text"=>"FANS",
        "url"=>"#",
        "active"=>FALSE
    ],
    [
        "text"=>"NEWS",
        "url"=>"#",
        "active"=>FALSE
    ],
    [
        "text"=>"SHOP",
        "url"=>"#",
        "active"=>FALSE
    ],
]
?>